FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

EXPOSE 3000

CMD ["sh", "-c", "pnpm install && pnpm dev"]
