# Generated by Django 6.0.3 on 2026-03-29 17:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("developers", "0002_oauthaccesstoken_oauthauthorizationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityServer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("region", models.CharField(db_index=True, max_length=50)),
                ("max_players", models.PositiveIntegerField(default=100)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline"), ("maintenance", "Maintenance")],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("server_version", models.CharField(blank=True, max_length=50)),
                ("custom_config", models.JSONField(blank=True, default=dict)),
                ("allowed_plugins", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servers",
                        to="developers.developerapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
