# Generated by Django 6.0.3 on 2026-03-10 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'shop categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('cosmetic', 'Cosmetic'), ('boost', 'Boost'), ('currency', 'Currency')], default='cosmetic', max_length=20)),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in game currency')),
                ('icon', models.CharField(blank=True, default='🎁', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shopcategory')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
