# Generated by Django 6.0.3 on 2026-03-29 17:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_anticheatviolation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("aggregate_type", models.CharField(db_index=True, max_length=50)),
                ("aggregate_id", models.CharField(db_index=True, max_length=100)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["published", "created_at"], name="game_outbox_publish_80abd8_idx")],
            },
        ),
    ]
